name: Computer Club of Western Michigan University
markdown: redcarpet
highligher: pygments
navigation:
    - text: Blog
      url: /blog/
    - text: Minutes
      url: /minutes/
    - text: Join
      url: /membership/
    - text: Wiki
      url: /wiki/
      target: wiki
    - text: Plan
      url: http://whatistheplan.com/
      target: plan
