# Site
name: CCoWMU
title: Computer Club of Western Michigan University
email: cclub@yakko.cs.wmich.edu
description: "The computer club of western michigan university."
baseurl: ""
url: "http://ccowmu.org/"
navigation:
    - text: Blog
      url: /blog/
    - text: Minutes
      url: /minutes/
    - text: Join
      url: /membership/
    - text: Wiki
      url: /wiki/
      target: wiki
    - text: Plan
      url: http://whatistheplan.com/
      target: plan
    - text: Resources
      url: https://docs.google.com/spreadsheets/d/1xu2KecrYhB7hOrpHmUpcEsCBsClqEET5DPCA5GFhSHg/edit#gid=0
      target: resources

# Build
markdown: redcarpet
highligher: pygments
